apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-s4mn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-s4mn
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-s4mn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-s4mn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-s4mn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-upfd-tenant/private-devfile/private-quarkus-devfile-sample-s4mn@sha256:015cb7ea92c63bdf294e3e48d93f2bdfc6f372b6720edb83c7f1ede5f7a80145
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
